{% set name = "flower" %}
{% set version = "0.9.3" %}
{% set sha256 = "7f45acb297ab7cf3dd40140816143a2588f6938dbd70b8c46b59c7d8d1e93d55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - flower = flower.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - celery >=3.1.0
    - tornado >=4.2.0
    - babel >=1.0
    - pytz
    - futures  # [py27]

test:
  imports:
    - flower
    - flower.api
    - flower.utils
    - flower.utils.backports
    - flower.views

  commands:
    - flower --help
    
  requires:
    - mock
    
about:
    home: https://github.com/mher/flower
    license: BSD 3-Clause
    summary: Celery Flower
    license_file: LICENSE

extra:
    recipe-maintainers:
        - kwilcox
        - ukaratay
