{% set name = "flower" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flower-{{ version }}.tar.gz
  sha256: 46493c7e8d9ca2167e8a46eb97ae8d280997cb40a81993230124d74f0fe40bac

build:
  number: 1
  entry_points:
    - flower = flower.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - celery >=5.0.5
    - humanize
    - prometheus_client >=0.8.0
    - pytz
    - tornado >=5.0.0,<7.0.0

test:
  imports:
    - flower
    - flower.api
  # pip check fails due to a problem in celery, not flower.
  # requires:
  #   - pip
  commands:
    # - pip check
    - flower --help

about:
  home: https://github.com/mher/flower
  license: BSD-3-Clause
  summary: Celery Flower
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ukaratay
    - thebestnom
