appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: FWCNzA4wsfrBkVrlrAPuVvH1HXDMUdpDiuJQJe/23BHORoX9wk+/6QIs5F5Adx7NSNqDjnsby8U82kARbDooZHiQuY3OwPWB5X35BIVlJpwGJaJ5hFlmF3E4k6s7Oipryp0ujvoNMVVgbMZMh/adm/FEmdQJcYwfTXDiRE7NN3CrvIb1h5BCFlywYwDR61Owqehp191CL2yVs7tOWFUcD96zO2kG6itrrGX9Vn0RIfEOdr1NkPx73V8udUXPsJk934+Gn+PUOSJ5vnnZTOOiFLibw+c/oNrWYJhC2hFOnxATEUsbCRrti33crfG/cdCgAhrlQBeh5Xr3qIobSj6VyIT7mHdCBYS21LP6Airz0jjQ0oqnA1PVgwt0RA5FEOwHlfqgo/FX/BNbhFLmIAEeAVu+167PgnhMs+t9+m4eOm8tDkSYicW/cpMtk7Pj/nN3gGYxYAwZwijDTxKYfJDhAKU9uVakG1VydCqqW/5DzdAJgmxCuivPcc2bOSEo/oXNS2lzPw7Egklst3ihHPqTDl2c7H3gBS0IGW1AOn/zrCaMewDWpXrTtG7mOBG3xa/Jkb0fH7/BuXC9mtkNU2iSYxMEiJZDILfi87AIST9VJAZHgqFWYnXbnV1BhUBk27XqeFfxoMuFZ0+YhloXm0/BH7QDx/hkaHQqUz5dKhJYOms=}
provider:
  win: azure
conda_forge_output_validation: true
